<?php

namespace AppBundle\Repository;

/**
 * DropboxRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DropboxRepository extends \Doctrine\ORM\EntityRepository
{
}
