AppBundle\Entity\Dropbox:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\DropboxRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        userid:
            type: integer
            unique: true
        token:
            type: string
            length: 255
    lifecycleCallbacks: {  }
